name: Update edgebr's Dev MedtrackWeb Submodule
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  update_submodules:
    name: Update EdgeBr Submodule
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token : ${{secrets.SERVICE_TOKEN}}
        repository: edgebr/pds-2022-2-03
        submodules : true
    - name: Update Repo
      run: |
        git checkout develop
        git config -f .gitmodules submodule.MedtrackWeb.branch dev
        git submodule update --init --recursive --remote MedtrackWeb
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update MedtrackWeb submodule from changes at TaigoI/MedtrackWeb (${{github.event.repository.updated_at}})"
        git push